language: cpp
install: make
compiler:
- g++
branches:
only:
- master
os:
- osx
notifications:
  email: false
before_install: sh travis/before-install.sh
script: sh travis/run-test.sh
before_install:
  - git submodule update --init --recursive